import React from'react';import{ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View,ViewStyle}from'react-native';import{C,statusColors}from'./theme';
export function Screen({children,scroll=true,refreshControl}:any){const content=<View style={s.content}>{children}</View>;return<SafeAreaView style={s.safe}>{scroll?<ScrollView keyboardShouldPersistTaps="handled" refreshControl={refreshControl} contentContainerStyle={{flexGrow:1}}>{content}</ScrollView>:content}</SafeAreaView>}
export function Header({title,subtitle,right}:any){return<View style={s.header}><View style={{flex:1}}><Text style={s.title}>{title}</Text>{subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View>{right}</View>}
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}){return<View style={[s.card,style]}>{children}</View>}
export function Button({title,onPress,kind='primary',disabled=false}:any){return<Pressable disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,kind==='ghost'&&s.buttonGhost,kind==='danger'&&s.buttonDanger,(pressed||disabled)&&{opacity:.65}]}><Text style={[s.buttonText,kind==='ghost'&&{color:C.text}]}>{title}</Text></Pressable>}
export function Input({label,error,...props}:any){return<View style={{gap:6}}>{label&&<Text style={s.label}>{label}</Text>}<TextInput placeholderTextColor="#9AA3AF" style={[s.input,error&&{borderColor:C.danger}]} {...props}/>{error&&<Text style={{color:C.danger,fontSize:12}}>{error}</Text>}</View>}
export function Badge({status,label}:any){const color=statusColors[status]||C.muted;return<View style={{backgroundColor:`${color}18`,paddingHorizontal:10,paddingVertical:5,borderRadius:20,alignSelf:'flex-start'}}><Text style={{color,fontSize:11,fontWeight:'800'}}>{label||String(status||'').replaceAll('_',' ')}</Text></View>}
export function Empty({title='Sin información',text='Los datos aparecerán aquí cuando sean registrados.'}:any){return<View style={s.empty}><Text style={{fontSize:34}}>◷</Text><Text style={{fontSize:16,fontWeight:'800',color:C.text}}>{title}</Text><Text style={{fontSize:13,color:C.muted,textAlign:'center'}}>{text}</Text></View>}
export function Loading(){return<View style={s.empty}><ActivityIndicator size="large" color={C.primary}/><Text style={{color:C.muted}}>Sincronizando…</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},content:{padding:18,gap:16,flex:1},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:4},title:{fontSize:28,fontWeight:'900',color:C.text,letterSpacing:-.6},subtitle:{fontSize:14,color:C.muted,marginTop:3},card:{backgroundColor:C.surface,borderWidth:1,borderColor:C.border,borderRadius:18,padding:16,shadowColor:'#0F172A',shadowOpacity:.06,shadowRadius:12,elevation:2},label:{fontSize:12,fontWeight:'800',color:C.muted,textTransform:'uppercase'},input:{height:52,borderWidth:1,borderColor:C.border,borderRadius:13,paddingHorizontal:15,fontSize:16,color:C.text,backgroundColor:'#FAFCFF'},button:{minHeight:50,borderRadius:13,backgroundColor:C.primary,alignItems:'center',justifyContent:'center',paddingHorizontal:18},buttonGhost:{backgroundColor:'#F1F4F8',borderWidth:1,borderColor:C.border},buttonDanger:{backgroundColor:C.danger},buttonText:{color:'#fff',fontSize:15,fontWeight:'800'},empty:{flex:1,minHeight:220,alignItems:'center',justifyContent:'center',gap:9,padding:28}});
export const styles=s;
