-- Radar 360 - Esquema completo PostgreSQL
-- Generado a partir de radar-360-backend/prisma/schema.prisma
-- Ejecutar dentro de una base de datos PostgreSQL vacía.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS clientes (
    id_cliente       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni              VARCHAR(20) NOT NULL UNIQUE,
    telefono         VARCHAR(20),
    nombres          VARCHAR(150) NOT NULL,
    apellido_paterno VARCHAR(100) NOT NULL,
    apellido_materno VARCHAR(100) NOT NULL,
    direccion        VARCHAR(255),
    distrito         VARCHAR(100),
    deuda_castigada  NUMERIC(12, 2) NOT NULL DEFAULT 0,
    deuda_vigente    NUMERIC(12, 2) NOT NULL DEFAULT 0,
    otras_deudas     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    estado           VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    ultima_gestion   TIMESTAMP(3),
    latitud          NUMERIC(10, 8),
    longitud         NUMERIC(11, 8)
);

CREATE TABLE IF NOT EXISTS asesores (
    id_asesor        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni              VARCHAR(20) NOT NULL UNIQUE,
    nombres          VARCHAR(150) NOT NULL,
    apellido_paterno VARCHAR(100) NOT NULL,
    apellido_materno VARCHAR(100) NOT NULL,
    telefono         VARCHAR(20),
    correo           VARCHAR(150),
    distrito         VARCHAR(100),
    estado           VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    latitud          NUMERIC(10, 8),
    longitud         NUMERIC(11, 8),
    fecha_creacion   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizar TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username       VARCHAR(50) NOT NULL UNIQUE,
    password_hash  TEXT NOT NULL,
    rol            VARCHAR(20) NOT NULL,
    estado         VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    id_asesor      INTEGER UNIQUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_asesor_fk
        FOREIGN KEY (id_asesor) REFERENCES asesores(id_asesor)
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS admisiones (
    id_admision   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente    INTEGER NOT NULL,
    producto      VARCHAR(150),
    linea_credito NUMERIC(12, 2),
    estado        VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha         TIMESTAMP(3),
    CONSTRAINT admisiones_cliente_fk
        FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS rutas (
    id_ruta           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asesor         INTEGER NOT NULL,
    fecha_programada  TIMESTAMP(3) NOT NULL,
    fecha_inicio_real TIMESTAMP(3),
    fecha_fin_real    TIMESTAMP(3),
    estado            VARCHAR(20) NOT NULL DEFAULT 'PROGRAMADA',
    fecha_creacion    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizar  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rutas_asesor_fk
        FOREIGN KEY (id_asesor) REFERENCES asesores(id_asesor)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS asignaciones_clientes (
    id_asignacion    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente       INTEGER NOT NULL,
    id_asesor        INTEGER NOT NULL,
    fecha_asignacion TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_fin        TIMESTAMP(3),
    estado           VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
    CONSTRAINT asignaciones_cliente_fk
        FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT asignaciones_asesor_fk
        FOREIGN KEY (id_asesor) REFERENCES asesores(id_asesor)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS rutas_clientes (
    id_ruta_cliente  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ruta          INTEGER NOT NULL,
    id_cliente       INTEGER NOT NULL,
    secuencia        INTEGER NOT NULL DEFAULT 0,
    estado_visita    VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    prioridad        VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
    fecha_creacion   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizar TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rutas_clientes_ruta_fk
        FOREIGN KEY (id_ruta) REFERENCES rutas(id_ruta)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT rutas_clientes_cliente_fk
        FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT rutas_clientes_ruta_cliente_unique UNIQUE (id_ruta, id_cliente)
);

CREATE TABLE IF NOT EXISTS visitas (
    id_visita          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ruta_cliente    INTEGER,
    id_cliente         INTEGER NOT NULL,
    id_asesor          INTEGER NOT NULL,
    tipo_visita        VARCHAR(20) NOT NULL DEFAULT 'PROGRAMADA',
    fecha_hora_checkin TIMESTAMP(3) NOT NULL,
    fecha_hora_checkout TIMESTAMP(3),
    latitud            NUMERIC(10, 8) NOT NULL,
    longitud           NUMERIC(11, 8) NOT NULL,
    resultado          VARCHAR(50) NOT NULL,
    es_efectiva        BOOLEAN NOT NULL DEFAULT FALSE,
    monto_recaudado    NUMERIC(12, 2),
    fecha_promesa      TIMESTAMP(3),
    observaciones      TEXT,
    foto_url           VARCHAR(255),
    fecha_creacion     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizar   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT visitas_ruta_cliente_fk
        FOREIGN KEY (id_ruta_cliente) REFERENCES rutas_clientes(id_ruta_cliente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT visitas_cliente_fk
        FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT visitas_asesor_fk
        FOREIGN KEY (id_asesor) REFERENCES asesores(id_asesor)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS clientes_latitud_longitud_idx
    ON clientes(latitud, longitud);

CREATE INDEX IF NOT EXISTS asignaciones_clientes_asesor_idx
    ON asignaciones_clientes(id_asesor);

CREATE INDEX IF NOT EXISTS asignaciones_clientes_cliente_idx
    ON asignaciones_clientes(id_cliente);

CREATE INDEX IF NOT EXISTS rutas_asesor_fecha_idx
    ON rutas(id_asesor, fecha_programada);

CREATE INDEX IF NOT EXISTS rutas_fecha_idx
    ON rutas(fecha_programada);

CREATE INDEX IF NOT EXISTS rutas_clientes_cliente_idx
    ON rutas_clientes(id_cliente);

CREATE INDEX IF NOT EXISTS visitas_ruta_cliente_idx
    ON visitas(id_ruta_cliente);

CREATE INDEX IF NOT EXISTS visitas_cliente_idx
    ON visitas(id_cliente);

CREATE INDEX IF NOT EXISTS visitas_asesor_fecha_idx
    ON visitas(id_asesor, fecha_hora_checkin);

-- Usuario administrador inicial.
-- Contraseña: Radar360#2026
INSERT INTO usuarios (username, password_hash, rol, estado)
VALUES (
    'admin',
    '$2b$10$YVN4U62FdfBxpj/YEyRZGuPNgvAVBmj3lrgBYiv0oyv4uZxSEwL.a',
    'ADMIN',
    'ACTIVO'
)
ON CONFLICT (username) DO NOTHING;

COMMIT;
