import{Router}from'express';
import controller from'../controllers/calidad.controller.js';
import{authMiddleware}from'../middlewares/auth.middleware.js';
import{roleMiddleware}from'../middlewares/role.middleware.js';
import{ROLES}from'../security/roles.js';
const router=Router();
const readers=[ROLES.ADMINISTRADOR,ROLES.GERENTE,ROLES.SUPERVISOR,ROLES.AUDITOR];
const editors=[ROLES.ADMINISTRADOR,ROLES.GERENTE,ROLES.SUPERVISOR];
router.use(authMiddleware);
router.get('/metricas',roleMiddleware(readers),controller.metricas);
router.get('/',roleMiddleware(readers),controller.listar);
router.get('/:id',roleMiddleware(readers),controller.obtener);
router.post('/',roleMiddleware(editors),controller.crear);
router.patch('/:id',roleMiddleware(editors),controller.actualizar);
export default router;
